name: ClansAU-Clans
main: com.areeoh.clans.Clans
version: 1.0
author: ClansAU Team
depend: [ClansAU-Core]
commands:
  clan:
    aliases: [c]
  clanchat:
    aliases: [cc]
  allychat:
    aliases: [ac]
  map:
  spawn:
  shop:
    aliases: [shops]